language: node_js
node_js: "10.15"
cache: yarn

_production-job: &production-job
  stage: production
  name: SERVICE_NAME
  script: scripts/deploy.js SERVICE_NAME
  install: skip
  env:
    - "ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm"

# _staging-job: &staging-job
#   stage: staging
#   name: SERVICE_NAME
#   script: scripts/deploy.js SERVICE_NAME
#   install: skip
#   env:
#     - "ENVIRONMENT=staging RANCHER_CLUSTERID=c-njflm"

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

  # - name: staging-started
  #   if: tag is present
  # - name: staging
  #   if: tag is present
  # - name: staging-finished
  #   if: tag is present

jobs:
  include:
    - stage: test
      env: [NODE_ENV=test]

    - <<: *production-job
      stage: production-started
      name: Deployment Started
      script: npx @parameter1/base-cms-website-deployment-tool notify-started
    # - <<: *staging-job
    #   stage: staging-started
    #   name: Deployment Started
    #   script: npx @parameter1/base-cms-website-deployment-tool notify-started

    ##########################
    # vvv ADD SITES HERE vvv #
    ##########################

    - <<: *production-job
      name: ccjdigital.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy ccjdigital.com virgon-websites
    - <<: *production-job
      name: ccjdigital.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy ccjdigital.com leonis-websites
    # - <<: *staging-job
    #   name: ccjdigital.com
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy ccjdigital.com staging-websites-virgon

    - <<: *production-job
      name: equipmentworld.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy equipmentworld.com virgon-websites
    - <<: *production-job
      name: equipmentworld.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy equipmentworld.com leonis-websites
    # - <<: *staging-job
    #   name: equipmentworld.com
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy equipmentworld.com staging-websites-virgon

    - <<: *production-job
      name: hardworkingtrucks.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy hardworkingtrucks.com virgon-websites
    - <<: *production-job
      name: hardworkingtrucks.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy hardworkingtrucks.com leonis-websites
    # - <<: *staging-job
    #   name: hardworkingtrucks.com
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy hardworkingtrucks.com staging-websites-virgon

    - <<: *production-job
      name: overdriveonline.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy overdriveonline.com virgon-websites
    - <<: *production-job
      name: overdriveonline.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy overdriveonline.com leonis-websites
    # - <<: *staging-job
    #   name: overdriveonline.com
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy overdriveonline.com staging-websites-virgon

    - <<: *production-job
      name: totallandscapecare.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy totallandscapecare.com virgon-websites
    - <<: *production-job
      name: totallandscapecare.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy totallandscapecare.com leonis-websites
    # - <<: *staging-job
    #   name: totallandscapecare.com
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy totallandscapecare.com staging-websites-virgon

    - <<: *production-job
      name: truckersnews.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy truckersnews.com virgon-websites
    - <<: *production-job
      name: truckersnews.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy truckersnews.com leonis-websites
    # - <<: *staging-job
    #   name: truckersnews.com
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy truckersnews.com staging-websites-virgon

    - <<: *production-job
      name: truckpartsandservice.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy truckpartsandservice.com virgon-websites
    - <<: *production-job
      name: truckpartsandservice.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy truckpartsandservice.com leonis-websites
    # - <<: *staging-job
    #   name: truckpartsandservice.com
    #   script: npx @parameter1/base-cms-website-deployment-tool deploy truckpartsandservice.com staging-websites-virgon

    ##########################
    # ^^^ ADD SITES HERE ^^^ #
    ##########################

    - <<: *production-job
      stage: production-finished
      name: Deployment Finished
      script: npx @parameter1/base-cms-website-deployment-tool notify-finished
    # - <<: *staging-job
    #   stage: staging-finished
    #   name: Deployment Finished
    #   script: npx @parameter1/base-cms-website-deployment-tool notify-finished
