version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY-(unset)}
  RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY-(unset)}
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: ${SENDGRID_DEV_TO-support@parameter1.com}
  YARN_CACHE_FOLDER: /.yarn-cache
  IDENTITYX_GRAPHQL_URI: ${IDENTITYX_GRAPHQL_URI-https://identity-x.parameter1.com/graphql}
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://base-browse.virgon.base.parameter1.com/graphql}
  ALGOLIA_APP_ID: ${ALGOLIA_APP_ID-05JLREVGZ4}
  ALGOLIA_API_KEY: ${ALGOLIA_API_KEY}
  ALGOLIA_DEFAULT_INDEX: ${ALGOLIA_DEFAULT_INDEX-randallreilly_all_platform_content}

x-env-virgon-dev: &env-virgon-dev
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10103}
  OEMBED_URI: ${OEMBED_URI-https://host.docker.internal:10402}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10203}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10303}

x-env-leonis: &env-leonis
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.leonis.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.leonis.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.leonis.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.leonis.base.parameter1.com}

x-env-virgon: &env-virgon
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.virgon.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.virgon.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.virgon.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.virgon.base.parameter1.com}

x-site-command: &site-cmd
  entrypoint: ["node_modules/.bin/basecms-website"]
  command: ["dev", "index.js"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  eqw:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/equipmentworld.com
    environment:
      <<: *env
      <<: *env-virgon
      PORT: 80
      EXPOSED_PORT: 9801
      LIVERELOAD_PORT: 19801
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce562fd28860bc33b826d6
    ports:
      - "9801:80"
      - "19801:19801"

  tlc:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/totallandscapecare.com
    environment:
      <<: *env
      <<: *env-virgon
      PORT: 80
      EXPOSED_PORT: 9802
      LIVERELOAD_PORT: 19802
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce563dd28860bc33b829c5
    ports:
      - "9802:80"
      - "19802:19802"

  tn:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/truckersnews.com
    environment:
      <<: *env
      <<: *env-virgon
      PORT: 80
      EXPOSED_PORT: 9803
      LIVERELOAD_PORT: 19803
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce6131d28860bc33c5b786
    ports:
      - "9803:80"
      - "19803:19803"

  ccj:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/ccjdigital.com
    environment:
      <<: *env
      <<: *env-virgon
      PORT: 80
      EXPOSED_PORT: 9804
      LIVERELOAD_PORT: 19804
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce5519d28860bc33b80a42
    ports:
      - "9804:80"
      - "19804:19804"

  hwt:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/hardworkingtrucks.com
    environment:
      <<: *env
      <<: *env-virgon
      PORT: 80
      EXPOSED_PORT: 9805
      LIVERELOAD_PORT: 19805
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce557bd28860bc33b8140d
    ports:
      - "9805:80"
      - "19805:19805"

  ovd:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/overdriveonline.com
    environment:
      <<: *env
      <<: *env-virgon
      PORT: 80
      EXPOSED_PORT: 9806
      LIVERELOAD_PORT: 19806
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce561dd28860bc33b823ce
    ports:
      - "9806:80"
      - "19806:19806"

  tps:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/truckpartsandservice.com
    environment:
      <<: *env
      <<: *env-virgon
      PORT: 80
      EXPOSED_PORT: 9807
      LIVERELOAD_PORT: 19807
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce55abd28860bc33b818d0
    ports:
      - "9807:80"
      - "19807:19807"

  eeb:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/rrmarketplaceblog.com
    environment:
      <<: *env
      <<: *env-leonis
      PORT: 80
      EXPOSED_PORT: 9808
      LIVERELOAD_PORT: 19808
      TENANT_KEY: randallreilly_eeb
      SITE_ID: 60244672fb505f627f2e4c47
    ports:
      - "9808:80"
      - "19808:19808"
